import Link from "next/link";
import { SyncButton } from "../../../components/sync-button";

export default async function RepositoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const repositoryId = Number(id);
  const name = `repository ${id}`;
  return <div className="content"><div className="page-heading"><div><Link className="eyebrow" href="/repositories">← All repositories</Link><h1 style={{ textTransform: "capitalize" }}>{name}</h1><p className="subtle">Connected GitHub repository</p></div><SyncButton repositoryId={repositoryId} /></div><section className="grid stat-grid"><article className="card stat-card"><div className="label">Health score</div><div className="value">91 / 100</div><div className="trend">Healthy</div></article><article className="card stat-card"><div className="label">Open pull requests</div><div className="value">08</div><div className="trend">↗ 6% this week</div></article><article className="card stat-card"><div className="label">Open issues</div><div className="value">12</div><div className="trend">↘ 3% this week</div></article><article className="card stat-card"><div className="label">Contributors</div><div className="value">14</div><div className="trend">↗ 2 this month</div></article></section><section className="grid two-col"><article className="card"><div className="card-heading"><h2>Repository activity</h2><span className="subtle">Last 30 days</span></div><div className="empty-state"><p className="subtle">Activity charts arrive with the analytics engine in Phase 6.</p></div></article><article className="card"><div className="card-heading"><h2>Risk summary</h2><span className="badge">Preview</span></div><div className="empty-state"><p className="subtle">Pull-request risk analysis will appear here once GitHub data is connected.</p></div></article></section></div>;
}
