import Link from "next/link";
import { StatCard } from "../../components/stat-card";
import { ActivityChart, RiskDistribution } from "../../components/activity-chart";

export default function DashboardPage() {
  return <div className="content">
    <div className="page-heading"><div><div className="eyebrow">Workspace overview</div><h1>Good evening, Nyasa.</h1><p className="subtle">Here&apos;s what&apos;s happening across your connected repositories.</p></div><Link className="button" href="/repositories">+ Connect repository</Link></div>
    <section className="grid stat-grid" aria-label="Workspace statistics"><StatCard label="Connected repositories" value="04" trend="2 this month" /><StatCard label="Open pull requests" value="18" trend="12% this week" /><StatCard label="High-risk PRs" value="03" trend="Needs attention" /><StatCard label="Average health score" value="84" trend="4.2% this month" /></section>
    <section className="grid two-col"><article className="card"><div className="card-heading"><h2>Recent activity</h2><Link href="/dashboard">View all</Link></div><div className="activity-list"><div className="activity-item"><div className="activity-icon">↗</div><div><strong>PR #142 has a high risk score</strong><span>devinsight-api · 18 minutes ago</span></div></div><div className="activity-item"><div className="activity-icon">✓</div><div><strong>Repository sync completed</strong><span>frontend-platform · 1 hour ago</span></div></div><div className="activity-item"><div className="activity-icon">!</div><div><strong>Anomaly detected in commit activity</strong><span>data-pipeline · 3 hours ago</span></div></div><div className="activity-item"><div className="activity-icon">+</div><div><strong>New repository connected</strong><span>mobile-app · Yesterday</span></div></div></div></article><article className="card"><div className="card-heading"><h2>Workspace health</h2><span className="badge">Healthy</span></div><div className="health-ring"><div className="health-ring-content"><strong>84</strong><span>out of 100</span></div></div><div className="legend"><div><b>18</b><span>Open PRs</span></div><div><b>23</b><span>Open issues</span></div><div><b>31</b><span>Contributors</span></div></div></article></section>
    <section className="grid two-col"><article className="card"><div className="card-heading"><h2>Commit activity</h2><span className="subtle">Last 12 weeks</span></div><ActivityChart /></article><article className="card"><div className="card-heading"><h2>Risk distribution</h2><span className="subtle">18 open PRs</span></div><RiskDistribution /></article></section>
    <section className="card" style={{ marginTop: 18 }}><div className="card-heading"><h2>Connected repositories</h2><Link href="/repositories">Manage repositories</Link></div><div className="repo-list"><Link className="repo-row" href="/repositories/devinsight-api"><div><strong>devinsight-api</strong><span>github.com/devinsight/api · Synced 12 min ago</span></div><span className="badge">Healthy · 91</span></Link><Link className="repo-row" href="/repositories/frontend-platform"><div><strong>frontend-platform</strong><span>github.com/devinsight/frontend · Synced 1 hour ago</span></div><span className="badge">Healthy · 86</span></Link></div></section>
  </div>;
}
